### ISSUE TITLE
Possible typo in the paper

### ISSUE THREAD

**Issue by nLight** [DmitriiKh/FastBurgAlgorithmLibrary#2]
https://github.com/DmitriiKh/FastBurgAlgorithmLibrary/blob/529402a013636539c209e5b1972b2d56279d1bef/FastBurgAlgorithmLibrary/FastBurgAlgorithm128.cs#L294

I'm curious what if we try contacting the author and ask him.

**Comment by DmitriiKh** [comment]
Thanks for the idea. I've contacted the author. Hope he will find time to answer

**Comment by DmitriiKh** [comment]
Unfortunately the author of paper did not respond
