### ISSUE TITLE
Extract variables

### ISSUE THREAD

**Issue by nLight** [DmitriiKh/FastBurgAlgorithmLibrary#3]
https://github.com/DmitriiKh/FastBurgAlgorithmLibrary/blob/529402a013636539c209e5b1972b2d56279d1bef/FastBurgAlgorithmLibrary/FastBurgAlgorithm64.cs#L203

I'd maybe extract expressions like this one `_absolutePosition - _nHistoryLengthSamples + _iIterationCounter - indexRow` into variables with cool and descriptive names

**Comment by DmitriiKh** [comment]
Thank you for your comment.
New fields were introduced to improve readability
`_positionBeginning = _absolutePosition - _nHistoryLengthSamples;
 _positionEnd = _absolutePosition - 1;`
